apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: mi-namespace
  name: viewer-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list"]
