apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backend-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: backend-serviceaccount
    namespace: mi-namespace
roleRef:
  kind: ClusterRole
  name: pods-list-clusterrole
  apiGroup: rbac.authorization.k8s.io
